/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Condition = {
    Mint: 'MINT',
    Good: 'GOOD',
    Poor: 'POOR',
    NeedsReplacement: 'NEEDS_REPLACEMENT'
} as const;
export type Condition = typeof Condition[keyof typeof Condition];


export function ConditionFromJSON(json: any): Condition {
    return ConditionFromJSONTyped(json, false);
}

export function ConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Condition {
    return json as Condition;
}

export function ConditionToJSON(value?: Condition | null): any {
    return value as any;
}

