/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateLocationDto
 */
export interface CreateLocationDto {
	/**
	 *
	 * @type {string}
	 * @memberof CreateLocationDto
	 */
	name: string;
}

/**
 * Check if a given object implements the CreateLocationDto interface.
 */
export function instanceOfCreateLocationDto(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'name' in value;

	return isInstance;
}

export function CreateLocationDtoFromJSON(json: any): CreateLocationDto {
	return CreateLocationDtoFromJSONTyped(json, false);
}

export function CreateLocationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLocationDto {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		name: json['name']
	};
}

export function CreateLocationDtoToJSON(value?: CreateLocationDto | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		name: value.name
	};
}
