/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Power } from './Power';
import {
    PowerFromJSON,
    PowerFromJSONTyped,
    PowerToJSON,
} from './Power';
import type { VehicleType } from './VehicleType';
import {
    VehicleTypeFromJSON,
    VehicleTypeFromJSONTyped,
    VehicleTypeToJSON,
} from './VehicleType';

/**
 * 
 * @export
 * @interface CreateVehicleDto
 */
export interface CreateVehicleDto {
    /**
     * 
     * @type {string}
     * @memberof CreateVehicleDto
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateVehicleDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateVehicleDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateVehicleDto
     */
    vin?: string;
    /**
     * 
     * @type {VehicleType}
     * @memberof CreateVehicleDto
     */
    vehicleType: VehicleType;
    /**
     * 
     * @type {string}
     * @memberof CreateVehicleDto
     */
    make: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVehicleDto
     */
    model: string;
    /**
     * 
     * @type {number}
     * @memberof CreateVehicleDto
     */
    machineHours?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateVehicleDto
     */
    link?: string;
    /**
     * 
     * @type {Power}
     * @memberof CreateVehicleDto
     */
    power: Power;
}

/**
 * Check if a given object implements the CreateVehicleDto interface.
 */
export function instanceOfCreateVehicleDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "vehicleType" in value;
    isInstance = isInstance && "make" in value;
    isInstance = isInstance && "model" in value;
    isInstance = isInstance && "power" in value;

    return isInstance;
}

export function CreateVehicleDtoFromJSON(json: any): CreateVehicleDto {
    return CreateVehicleDtoFromJSONTyped(json, false);
}

export function CreateVehicleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVehicleDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'vin': !exists(json, 'vin') ? undefined : json['vin'],
        'vehicleType': VehicleTypeFromJSON(json['vehicleType']),
        'make': json['make'],
        'model': json['model'],
        'machineHours': !exists(json, 'machineHours') ? undefined : json['machineHours'],
        'link': !exists(json, 'link') ? undefined : json['link'],
        'power': PowerFromJSON(json['power']),
    };
}

export function CreateVehicleDtoToJSON(value?: CreateVehicleDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'vin': value.vin,
        'vehicleType': VehicleTypeToJSON(value.vehicleType),
        'make': value.make,
        'model': value.model,
        'machineHours': value.machineHours,
        'link': value.link,
        'power': PowerToJSON(value.power),
    };
}

