/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateToolDto
 */
export interface CreateToolDto {
    /**
     * The name of the tool.
     * @type {string}
     * @memberof CreateToolDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateToolDto
     */
    maintenanceTaskId?: string;
}

/**
 * Check if a given object implements the CreateToolDto interface.
 */
export function instanceOfCreateToolDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateToolDtoFromJSON(json: any): CreateToolDto {
    return CreateToolDtoFromJSONTyped(json, false);
}

export function CreateToolDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateToolDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'maintenanceTaskId': !exists(json, 'maintenanceTaskId') ? undefined : json['maintenanceTaskId'],
    };
}

export function CreateToolDtoToJSON(value?: CreateToolDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'maintenanceTaskId': value.maintenanceTaskId,
    };
}

