/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateVehicleDto
 */
export interface CreateVehicleDto {
	/**
	 *
	 * @type {string}
	 * @memberof CreateVehicleDto
	 */
	name: string;
	/**
	 *
	 * @type {string}
	 * @memberof CreateVehicleDto
	 */
	make?: string;
	/**
	 *
	 * @type {string}
	 * @memberof CreateVehicleDto
	 */
	model: string;
	/**
	 *
	 * @type {number}
	 * @memberof CreateVehicleDto
	 */
	year: number;
	/**
	 *
	 * @type {number}
	 * @memberof CreateVehicleDto
	 */
	hours: number;
	/**
	 *
	 * @type {boolean}
	 * @memberof CreateVehicleDto
	 */
	active?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof CreateVehicleDto
	 */
	power?: CreateVehicleDtoPowerEnum;
	/**
	 *
	 * @type {string}
	 * @memberof CreateVehicleDto
	 */
	locationId?: string;
	/**
	 *
	 * @type {string}
	 * @memberof CreateVehicleDto
	 */
	tagName?: string;
}

/**
 * @export
 */
export const CreateVehicleDtoPowerEnum = {
	Gas: 'GAS',
	Diesel: 'DIESEL',
	Electric: 'ELECTRIC',
	Hybrid: 'HYBRID'
} as const;
export type CreateVehicleDtoPowerEnum = typeof CreateVehicleDtoPowerEnum[keyof typeof CreateVehicleDtoPowerEnum];

/**
 * Check if a given object implements the CreateVehicleDto interface.
 */
export function instanceOfCreateVehicleDto(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'name' in value;
	isInstance = isInstance && 'model' in value;
	isInstance = isInstance && 'year' in value;
	isInstance = isInstance && 'hours' in value;

	return isInstance;
}

export function CreateVehicleDtoFromJSON(json: any): CreateVehicleDto {
	return CreateVehicleDtoFromJSONTyped(json, false);
}

export function CreateVehicleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVehicleDto {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		name: json['name'],
		make: !exists(json, 'make') ? undefined : json['make'],
		model: json['model'],
		year: json['year'],
		hours: json['hours'],
		active: !exists(json, 'active') ? undefined : json['active'],
		power: !exists(json, 'power') ? undefined : json['power'],
		locationId: !exists(json, 'locationId') ? undefined : json['locationId'],
		tagName: !exists(json, 'tagName') ? undefined : json['tagName']
	};
}

export function CreateVehicleDtoToJSON(value?: CreateVehicleDto | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		name: value.name,
		make: value.make,
		model: value.model,
		year: value.year,
		hours: value.hours,
		active: value.active,
		power: value.power,
		locationId: value.locationId,
		tagName: value.tagName
	};
}
