/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Condition } from './Condition';
import {
    ConditionFromJSON,
    ConditionFromJSONTyped,
    ConditionToJSON,
} from './Condition';

/**
 * 
 * @export
 * @interface CreateVehiclePartDto
 */
export interface CreateVehiclePartDto {
    /**
     * 
     * @type {string}
     * @memberof CreateVehiclePartDto
     */
    name: string;
    /**
     * 
     * @type {Condition}
     * @memberof CreateVehiclePartDto
     */
    condition?: Condition;
    /**
     * 
     * @type {number}
     * @memberof CreateVehiclePartDto
     */
    hours?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateVehiclePartDto
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVehiclePartDto
     */
    vehicleId?: string;
}

/**
 * Check if a given object implements the CreateVehiclePartDto interface.
 */
export function instanceOfCreateVehiclePartDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateVehiclePartDtoFromJSON(json: any): CreateVehiclePartDto {
    return CreateVehiclePartDtoFromJSONTyped(json, false);
}

export function CreateVehiclePartDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVehiclePartDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'condition': !exists(json, 'condition') ? undefined : ConditionFromJSON(json['condition']),
        'hours': !exists(json, 'hours') ? undefined : json['hours'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'vehicleId': !exists(json, 'vehicleId') ? undefined : json['vehicleId'],
    };
}

export function CreateVehiclePartDtoToJSON(value?: CreateVehiclePartDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'condition': ConditionToJSON(value.condition),
        'hours': value.hours,
        'notes': value.notes,
        'vehicleId': value.vehicleId,
    };
}

