/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateImplementDto
 */
export interface CreateImplementDto {
    /**
     * 
     * @type {string}
     * @memberof CreateImplementDto
     */
    name: string;
    /**
     * 
     * @type {object}
     * @memberof CreateImplementDto
     */
    condition?: object;
    /**
     * 
     * @type {string}
     * @memberof CreateImplementDto
     */
    locationId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateImplementDto
     */
    tagName?: string;
}

/**
 * Check if a given object implements the CreateImplementDto interface.
 */
export function instanceOfCreateImplementDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateImplementDtoFromJSON(json: any): CreateImplementDto {
    return CreateImplementDtoFromJSONTyped(json, false);
}

export function CreateImplementDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateImplementDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'condition': !exists(json, 'condition') ? undefined : json['condition'],
        'locationId': !exists(json, 'locationId') ? undefined : json['locationId'],
        'tagName': !exists(json, 'tagName') ? undefined : json['tagName'],
    };
}

export function CreateImplementDtoToJSON(value?: CreateImplementDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'condition': value.condition,
        'locationId': value.locationId,
        'tagName': value.tagName,
    };
}

