/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmployeeResponse
 */
export interface EmployeeResponse {
    /**
     * 
     * @type {string}
     * @memberof EmployeeResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EmployeeResponse
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof EmployeeResponse
     */
    name: string;
}

/**
 * Check if a given object implements the EmployeeResponse interface.
 */
export function instanceOfEmployeeResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function EmployeeResponseFromJSON(json: any): EmployeeResponse {
    return EmployeeResponseFromJSONTyped(json, false);
}

export function EmployeeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'name': json['name'],
    };
}

export function EmployeeResponseToJSON(value?: EmployeeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'name': value.name,
    };
}

