/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EquipmentResponse
 */
export interface EquipmentResponse {
	/**
	 *
	 * @type {string}
	 * @memberof EquipmentResponse
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof EquipmentResponse
	 */
	name: string;
	/**
	 *
	 * @type {object}
	 * @memberof EquipmentResponse
	 */
	condition?: object;
	/**
	 *
	 * @type {string}
	 * @memberof EquipmentResponse
	 */
	locationId?: string;
	/**
	 *
	 * @type {string}
	 * @memberof EquipmentResponse
	 */
	tagName?: string;
	/**
	 *
	 * @type {Date}
	 * @memberof EquipmentResponse
	 */
	createdAt: Date;
	/**
	 *
	 * @type {Date}
	 * @memberof EquipmentResponse
	 */
	updatedAt: Date;
}

/**
 * Check if a given object implements the EquipmentResponse interface.
 */
export function instanceOfEquipmentResponse(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'id' in value;
	isInstance = isInstance && 'name' in value;
	isInstance = isInstance && 'createdAt' in value;
	isInstance = isInstance && 'updatedAt' in value;

	return isInstance;
}

export function EquipmentResponseFromJSON(json: any): EquipmentResponse {
	return EquipmentResponseFromJSONTyped(json, false);
}

export function EquipmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentResponse {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		id: json['id'],
		name: json['name'],
		condition: !exists(json, 'condition') ? undefined : json['condition'],
		locationId: !exists(json, 'locationId') ? undefined : json['locationId'],
		tagName: !exists(json, 'tagName') ? undefined : json['tagName'],
		createdAt: new Date(json['createdAt']),
		updatedAt: new Date(json['updatedAt'])
	};
}

export function EquipmentResponseToJSON(value?: EquipmentResponse | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		id: value.id,
		name: value.name,
		condition: value.condition,
		locationId: value.locationId,
		tagName: value.tagName,
		createdAt: value.createdAt.toISOString(),
		updatedAt: value.updatedAt.toISOString()
	};
}
