/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImplementResponse
 */
export interface ImplementResponse {
    /**
     * 
     * @type {string}
     * @memberof ImplementResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ImplementResponse
     */
    name: string;
    /**
     * 
     * @type {object}
     * @memberof ImplementResponse
     */
    condition?: object;
    /**
     * 
     * @type {string}
     * @memberof ImplementResponse
     */
    locationId?: string;
    /**
     * 
     * @type {string}
     * @memberof ImplementResponse
     */
    tagName?: string;
    /**
     * 
     * @type {Date}
     * @memberof ImplementResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ImplementResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ImplementResponse interface.
 */
export function instanceOfImplementResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function ImplementResponseFromJSON(json: any): ImplementResponse {
    return ImplementResponseFromJSONTyped(json, false);
}

export function ImplementResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImplementResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'condition': !exists(json, 'condition') ? undefined : json['condition'],
        'locationId': !exists(json, 'locationId') ? undefined : json['locationId'],
        'tagName': !exists(json, 'tagName') ? undefined : json['tagName'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ImplementResponseToJSON(value?: ImplementResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'condition': value.condition,
        'locationId': value.locationId,
        'tagName': value.tagName,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

