/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Power = {
    Gas: 'GAS',
    Diesel: 'DIESEL',
    Electric: 'ELECTRIC',
    Hybrid: 'HYBRID'
} as const;
export type Power = typeof Power[keyof typeof Power];


export function PowerFromJSON(json: any): Power {
    return PowerFromJSONTyped(json, false);
}

export function PowerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Power {
    return json as Power;
}

export function PowerToJSON(value?: Power | null): any {
    return value as any;
}

