/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TagResponse
 */
export interface TagResponse {
	/**
	 *
	 * @type {string}
	 * @memberof TagResponse
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof TagResponse
	 */
	name: string;
	/**
	 *
	 * @type {Date}
	 * @memberof TagResponse
	 */
	createdAt: Date;
	/**
	 *
	 * @type {Date}
	 * @memberof TagResponse
	 */
	updatedAt: Date;
}

/**
 * Check if a given object implements the TagResponse interface.
 */
export function instanceOfTagResponse(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'id' in value;
	isInstance = isInstance && 'name' in value;
	isInstance = isInstance && 'createdAt' in value;
	isInstance = isInstance && 'updatedAt' in value;

	return isInstance;
}

export function TagResponseFromJSON(json: any): TagResponse {
	return TagResponseFromJSONTyped(json, false);
}

export function TagResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagResponse {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		id: json['id'],
		name: json['name'],
		createdAt: new Date(json['createdAt']),
		updatedAt: new Date(json['updatedAt'])
	};
}

export function TagResponseToJSON(value?: TagResponse | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		id: value.id,
		name: value.name,
		createdAt: value.createdAt.toISOString(),
		updatedAt: value.updatedAt.toISOString()
	};
}
