/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateToolDto
 */
export interface UpdateToolDto {
    /**
     * The name of the tool.
     * @type {string}
     * @memberof UpdateToolDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateToolDto
     */
    maintenanceTaskId?: string;
}

/**
 * Check if a given object implements the UpdateToolDto interface.
 */
export function instanceOfUpdateToolDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateToolDtoFromJSON(json: any): UpdateToolDto {
    return UpdateToolDtoFromJSONTyped(json, false);
}

export function UpdateToolDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateToolDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'maintenanceTaskId': !exists(json, 'maintenanceTaskId') ? undefined : json['maintenanceTaskId'],
    };
}

export function UpdateToolDtoToJSON(value?: UpdateToolDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'maintenanceTaskId': value.maintenanceTaskId,
    };
}

