/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TaskStatus } from './TaskStatus';
import {
    TaskStatusFromJSON,
    TaskStatusFromJSONTyped,
    TaskStatusToJSON,
} from './TaskStatus';

/**
 * 
 * @export
 * @interface UpdateMaintenanceTaskDto
 */
export interface UpdateMaintenanceTaskDto {
    /**
     * 
     * @type {TaskStatus}
     * @memberof UpdateMaintenanceTaskDto
     */
    status?: TaskStatus;
    /**
     * 
     * @type {Date}
     * @memberof UpdateMaintenanceTaskDto
     */
    dueDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateMaintenanceTaskDto
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateMaintenanceTaskDto
     */
    completedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateMaintenanceTaskDto
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateMaintenanceTaskDto
     */
    machineHours?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateMaintenanceTaskDto
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMaintenanceTaskDto
     */
    assigneeId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMaintenanceTaskDto
     */
    vehicleId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMaintenanceTaskDto
     */
    guideId?: string;
}

/**
 * Check if a given object implements the UpdateMaintenanceTaskDto interface.
 */
export function instanceOfUpdateMaintenanceTaskDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateMaintenanceTaskDtoFromJSON(json: any): UpdateMaintenanceTaskDto {
    return UpdateMaintenanceTaskDtoFromJSONTyped(json, false);
}

export function UpdateMaintenanceTaskDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMaintenanceTaskDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : TaskStatusFromJSON(json['status']),
        'dueDate': !exists(json, 'dueDate') ? undefined : (new Date(json['dueDate'])),
        'startedAt': !exists(json, 'startedAt') ? undefined : (new Date(json['startedAt'])),
        'completedAt': !exists(json, 'completedAt') ? undefined : (new Date(json['completedAt'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'machineHours': !exists(json, 'machineHours') ? undefined : json['machineHours'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'assigneeId': !exists(json, 'assigneeId') ? undefined : json['assigneeId'],
        'vehicleId': !exists(json, 'vehicleId') ? undefined : json['vehicleId'],
        'guideId': !exists(json, 'guideId') ? undefined : json['guideId'],
    };
}

export function UpdateMaintenanceTaskDtoToJSON(value?: UpdateMaintenanceTaskDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': TaskStatusToJSON(value.status),
        'dueDate': value.dueDate === undefined ? undefined : (value.dueDate.toISOString()),
        'startedAt': value.startedAt === undefined ? undefined : (value.startedAt.toISOString()),
        'completedAt': value.completedAt === undefined ? undefined : (value.completedAt.toISOString()),
        'name': value.name,
        'machineHours': value.machineHours,
        'notes': value.notes,
        'assigneeId': value.assigneeId,
        'vehicleId': value.vehicleId,
        'guideId': value.guideId,
    };
}

