/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateImplementDto
 */
export interface UpdateImplementDto {
	/**
	 *
	 * @type {string}
	 * @memberof UpdateImplementDto
	 */
	name: string;
	/**
	 *
	 * @type {object}
	 * @memberof UpdateImplementDto
	 */
	condition?: object;
	/**
	 *
	 * @type {string}
	 * @memberof UpdateImplementDto
	 */
	locationId?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UpdateImplementDto
	 */
	tagName?: string;
}

/**
 * Check if a given object implements the UpdateImplementDto interface.
 */
export function instanceOfUpdateImplementDto(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'name' in value;

	return isInstance;
}

export function UpdateImplementDtoFromJSON(json: any): UpdateImplementDto {
	return UpdateImplementDtoFromJSONTyped(json, false);
}

export function UpdateImplementDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateImplementDto {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		name: json['name'],
		condition: !exists(json, 'condition') ? undefined : json['condition'],
		locationId: !exists(json, 'locationId') ? undefined : json['locationId'],
		tagName: !exists(json, 'tagName') ? undefined : json['tagName']
	};
}

export function UpdateImplementDtoToJSON(value?: UpdateImplementDto | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		name: value.name,
		condition: value.condition,
		locationId: value.locationId,
		tagName: value.tagName
	};
}
