/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEmployeeDto
 */
export interface UpdateEmployeeDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDto
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateEmployeeDto interface.
 */
export function instanceOfUpdateEmployeeDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateEmployeeDtoFromJSON(json: any): UpdateEmployeeDto {
    return UpdateEmployeeDtoFromJSONTyped(json, false);
}

export function UpdateEmployeeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmployeeDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function UpdateEmployeeDtoToJSON(value?: UpdateEmployeeDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

