/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMaintenanceGuideDto
 */
export interface UpdateMaintenanceGuideDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateMaintenanceGuideDto
     */
    vehicleId?: string;
}

/**
 * Check if a given object implements the UpdateMaintenanceGuideDto interface.
 */
export function instanceOfUpdateMaintenanceGuideDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateMaintenanceGuideDtoFromJSON(json: any): UpdateMaintenanceGuideDto {
    return UpdateMaintenanceGuideDtoFromJSONTyped(json, false);
}

export function UpdateMaintenanceGuideDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMaintenanceGuideDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vehicleId': !exists(json, 'vehicleId') ? undefined : json['vehicleId'],
    };
}

export function UpdateMaintenanceGuideDtoToJSON(value?: UpdateMaintenanceGuideDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vehicleId': value.vehicleId,
    };
}

