/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateToolDto
 */
export interface UpdateToolDto {
	/**
	 *
	 * @type {string}
	 * @memberof UpdateToolDto
	 */
	name: string;
	/**
	 *
	 * @type {object}
	 * @memberof UpdateToolDto
	 */
	condition?: object;
	/**
	 *
	 * @type {string}
	 * @memberof UpdateToolDto
	 */
	tagName?: string;
}

/**
 * Check if a given object implements the UpdateToolDto interface.
 */
export function instanceOfUpdateToolDto(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'name' in value;

	return isInstance;
}

export function UpdateToolDtoFromJSON(json: any): UpdateToolDto {
	return UpdateToolDtoFromJSONTyped(json, false);
}

export function UpdateToolDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateToolDto {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		name: json['name'],
		condition: !exists(json, 'condition') ? undefined : json['condition'],
		tagName: !exists(json, 'tagName') ? undefined : json['tagName']
	};
}

export function UpdateToolDtoToJSON(value?: UpdateToolDto | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		name: value.name,
		condition: value.condition,
		tagName: value.tagName
	};
}
