version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env

  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - postgres
