version: '3.8'

networks:
  inventory:
  proxy:
    external: true

volumes:
  postgres:
    name: inventory-db

services:
  inventory-ui:
    image: ghcr.io/brittonhayes/inventory-ui:latest
    restart: unless-stopped
    labels:
      caddy: "openfarms.brittonhayes.com"
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - inventory
      - proxy

  inventory-api:
    image: ghcr.io/brittonhayes/inventory-api:latest
    restart: unless-stopped
    networks:
      - inventory
      - proxy
    environment:
      PORT: ${PORT:-5000}
      DB_PORT: ${DB_PORT:-5432}
      DB_HOST: ${DB_HOST:-inventory-db}
      DB_SCHEMA: ${DB_SCHEMA:-inventory}
      DATABASE_URL: postgres://${POSTGRES_USER:-prisma}:${POSTGRES_PASSWORD:-topsecret}@inventory-db:5432/${POSTGRES_DB:-inventory}?schema=${DB_SCHEMA:-inventory}&sslmode=prefer
    labels:
      caddy: "openfarms.brittonhayes.com"
      caddy.0_handle: "/api*"
      caddy.0_handle.0_reverse_proxy: "{{upstreams 5000}}"
      caddy.1_handle: "/graphql"
      caddy.1_handle.0_reverse_proxy: "{{upstreams 5000}}"
      caddy.1_reverse_proxy: "@ws {{upstreams 5000}}"
      caddy.@ws.0_header: "Connection *Upgrade*"
      caddy.@ws.1_header: "Upgrade websocket"
    depends_on:
      - inventory-db

  inventory-db:
    image: postgres:15
    restart: unless-stopped
    networks:
      - inventory
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-prisma}
      POSTGRES_DB: ${POSTGRES_DB:-inventory}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-topsecret}
    volumes:
      - postgres:/var/lib/postgresql/data
