version: '3.8'
services:
  inventory-ui:
    image: ghcr.io/brittonhayes/inventory-ui:latest
    restart: unless-stopped
    environment:
      PUBLIC_API_BASE_URL: "inventory-api:5000"
    depends_on:
      - inventory-db
      - inventory-api

  inventory-api:
    image: ghcr.io/brittonhayes/inventory-api:latest
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_SCHEMA: ${DB_SCHEMA}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@inventory-db:5432/${POSTGRES_DB}?schema=${DB_SCHEMA}&sslmode=prefer
    depends_on:
      - inventory-db

  inventory-db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: inventory-db
