# https://taskfile.dev

version: '3'

includes:
  win: ./Taskfile_windows.yml

tasks:
  release:
    desc: "Release all docker images"
    cmds:
      - task: release:api:docker
      - task: release:ui:docker

  build:api:
    desc: "Build API"
    cmds:
      - earthly +docker
    dir: packages/inventory-api

  build:ui:
    desc: "Build UI"
    cmds:
      - earthly +docker
    dir: packages/inventory-ui

