/* tslint:disable */
/* eslint-disable */
/**
 * Open Farms Inventory Service
 * Agriculture inventory management service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateToolDto,
  ToolResponse,
  UpdateToolDto,
} from '../models';
import {
    CreateToolDtoFromJSON,
    CreateToolDtoToJSON,
    ToolResponseFromJSON,
    ToolResponseToJSON,
    UpdateToolDtoFromJSON,
    UpdateToolDtoToJSON,
} from '../models';

export interface ToolsControllerCreateToolRequest {
    createToolDto: CreateToolDto;
}

export interface ToolsControllerDeleteToolRequest {
    id: string;
}

export interface ToolsControllerFindToolByIdRequest {
    id: string;
}

export interface ToolsControllerListToolsRequest {
    name?: string;
    orderBy?: ToolsControllerListToolsOrderByEnum;
    sort?: ToolsControllerListToolsSortEnum;
}

export interface ToolsControllerUpdateToolRequest {
    id: string;
    updateToolDto: UpdateToolDto;
}

/**
 * 
 */
export class ToolsApi extends runtime.BaseAPI {

    /**
     */
    async toolsControllerCreateToolRaw(requestParameters: ToolsControllerCreateToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ToolResponse>> {
        if (requestParameters.createToolDto === null || requestParameters.createToolDto === undefined) {
            throw new runtime.RequiredError('createToolDto','Required parameter requestParameters.createToolDto was null or undefined when calling toolsControllerCreateTool.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/tools`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateToolDtoToJSON(requestParameters.createToolDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ToolResponseFromJSON(jsonValue));
    }

    /**
     */
    async toolsControllerCreateTool(requestParameters: ToolsControllerCreateToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ToolResponse> {
        const response = await this.toolsControllerCreateToolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async toolsControllerDeleteToolRaw(requestParameters: ToolsControllerDeleteToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ToolResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling toolsControllerDeleteTool.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/tools/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ToolResponseFromJSON(jsonValue));
    }

    /**
     */
    async toolsControllerDeleteTool(requestParameters: ToolsControllerDeleteToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ToolResponse> {
        const response = await this.toolsControllerDeleteToolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async toolsControllerFindToolByIdRaw(requestParameters: ToolsControllerFindToolByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ToolResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling toolsControllerFindToolById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/tools/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ToolResponseFromJSON(jsonValue));
    }

    /**
     */
    async toolsControllerFindToolById(requestParameters: ToolsControllerFindToolByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ToolResponse> {
        const response = await this.toolsControllerFindToolByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async toolsControllerListToolsRaw(requestParameters: ToolsControllerListToolsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ToolResponse>>> {
        const queryParameters: any = {};

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.orderBy !== undefined) {
            queryParameters['orderBy'] = requestParameters.orderBy;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/tools`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ToolResponseFromJSON));
    }

    /**
     */
    async toolsControllerListTools(requestParameters: ToolsControllerListToolsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ToolResponse>> {
        const response = await this.toolsControllerListToolsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async toolsControllerUpdateToolRaw(requestParameters: ToolsControllerUpdateToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ToolResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling toolsControllerUpdateTool.');
        }

        if (requestParameters.updateToolDto === null || requestParameters.updateToolDto === undefined) {
            throw new runtime.RequiredError('updateToolDto','Required parameter requestParameters.updateToolDto was null or undefined when calling toolsControllerUpdateTool.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/tools/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateToolDtoToJSON(requestParameters.updateToolDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ToolResponseFromJSON(jsonValue));
    }

    /**
     */
    async toolsControllerUpdateTool(requestParameters: ToolsControllerUpdateToolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ToolResponse> {
        const response = await this.toolsControllerUpdateToolRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ToolsControllerListToolsOrderByEnum = {
    Id: 'id',
    Name: 'name',
    MaintenanceTaskId: 'maintenanceTaskId'
} as const;
export type ToolsControllerListToolsOrderByEnum = typeof ToolsControllerListToolsOrderByEnum[keyof typeof ToolsControllerListToolsOrderByEnum];
/**
 * @export
 */
export const ToolsControllerListToolsSortEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ToolsControllerListToolsSortEnum = typeof ToolsControllerListToolsSortEnum[keyof typeof ToolsControllerListToolsSortEnum];
