// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​a​s​t​ ​u​p​d​a​t​e​d
	 */
	lastUpdated: string
	home: {
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		title: string
		/**
		 * W​o​r​k​ ​i​n​ ​p​r​o​g​r​e​s​s​ ​.​.​.
		 */
		subtitle: string
	}
	maintenance: {
		/**
		 * M​a​i​n​t​e​n​a​n​c​e
		 */
		title: string
		/**
		 * M​a​i​n​t​e​n​a​n​c​e​ ​t​a​s​k​s​ ​a​n​d​ ​g​u​i​d​e​s​.
		 */
		subtitle: string
	}
	tasks: {
		/**
		 * M​a​i​n​t​e​n​a​n​c​e​ ​T​a​s​k​s
		 */
		title: string
		/**
		 * L​i​s​t​ ​o​f​ ​m​a​i​n​t​e​n​a​n​c​e​ ​t​a​s​k​s​.
		 */
		subtitle: string
		table: {
			columns: {
				/**
				 * N​a​m​e
				 */
				name: string
				/**
				 * A​s​s​i​g​n​e​e
				 */
				assignee: string
				/**
				 * D​u​e​ ​d​a​t​e
				 */
				dueDate: string
			}
		}
	}
	vehicles: {
		/**
		 * V​e​h​i​c​l​e​s
		 */
		title: string
		/**
		 * Y​o​u​r​ ​c​u​r​r​e​n​t​l​y​ ​a​c​t​i​v​e​ ​v​e​h​i​c​l​e​s​.
		 */
		subtitle: string
		table: {
			columns: {
				/**
				 * N​a​m​e
				 */
				name: string
				/**
				 * M​a​k​e
				 */
				make: string
				/**
				 * M​o​d​e​l
				 */
				model: string
				/**
				 * H​o​u​r​s
				 */
				hours: string
				/**
				 * T​y​p​e
				 */
				type: string
			}
		}
	}
	employees: {
		/**
		 * E​m​p​l​o​y​e​e​s
		 */
		title: string
		/**
		 * L​i​s​t​ ​o​f​ ​e​m​p​l​o​y​e​e​s​.
		 */
		subtitle: string
		button: {
			/**
			 * A​d​d​ ​e​m​p​l​o​y​e​e
			 */
			add: string
		}
		table: {
			columns: {
				/**
				 * N​a​m​e
				 */
				name: string
			}
		}
	}
	/**
	 * T​h​i​s​ ​l​o​g​ ​w​a​s​ ​c​a​l​l​e​d​ ​f​r​o​m​ ​'​{​f​i​l​e​N​a​m​e​}​'
	 * @param {string} fileName
	 */
	log: RequiredParams<'fileName'>
}

export type TranslationFunctions = {
	/**
	 * Last updated
	 */
	lastUpdated: () => LocalizedString
	home: {
		/**
		 * Dashboard
		 */
		title: () => LocalizedString
		/**
		 * Work in progress ...
		 */
		subtitle: () => LocalizedString
	}
	maintenance: {
		/**
		 * Maintenance
		 */
		title: () => LocalizedString
		/**
		 * Maintenance tasks and guides.
		 */
		subtitle: () => LocalizedString
	}
	tasks: {
		/**
		 * Maintenance Tasks
		 */
		title: () => LocalizedString
		/**
		 * List of maintenance tasks.
		 */
		subtitle: () => LocalizedString
		table: {
			columns: {
				/**
				 * Name
				 */
				name: () => LocalizedString
				/**
				 * Assignee
				 */
				assignee: () => LocalizedString
				/**
				 * Due date
				 */
				dueDate: () => LocalizedString
			}
		}
	}
	vehicles: {
		/**
		 * Vehicles
		 */
		title: () => LocalizedString
		/**
		 * Your currently active vehicles.
		 */
		subtitle: () => LocalizedString
		table: {
			columns: {
				/**
				 * Name
				 */
				name: () => LocalizedString
				/**
				 * Make
				 */
				make: () => LocalizedString
				/**
				 * Model
				 */
				model: () => LocalizedString
				/**
				 * Hours
				 */
				hours: () => LocalizedString
				/**
				 * Type
				 */
				type: () => LocalizedString
			}
		}
	}
	employees: {
		/**
		 * Employees
		 */
		title: () => LocalizedString
		/**
		 * List of employees.
		 */
		subtitle: () => LocalizedString
		button: {
			/**
			 * Add employee
			 */
			add: () => LocalizedString
		}
		table: {
			columns: {
				/**
				 * Name
				 */
				name: () => LocalizedString
			}
		}
	}
	/**
	 * This log was called from '{fileName}'
	 */
	log: (arg: { fileName: string }) => LocalizedString
}

export type Formatters = {}
